name: frontend
description: "Kairos — Social media platform for students."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # HTTP & API
  dio: ^5.7.0

  # SignalR
  signalr_netcore: ^1.3.5

  # File picking & image
  image_picker: ^1.1.2
  file_picker: ^8.1.2

  # PDF preview
  flutter_pdfview: ^1.3.2

  # State management
  flutter_riverpod: ^2.5.1

  # Auth token persistence
  flutter_secure_storage: ^9.2.2

  # Path utilities
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
